### ISSUE TITLE
Release Checklist 1.0.0

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/tts#220]
A simple list to ensure things won't be forgotten
- [x] Consistency of REST Api
- [x] Documentation
- [x] Unit Test coverage
- [x] integration testing
- [x] wattson released
- [x] release version of oidcc_cowboy
- [x] release version of oidcc
- [x] released plugins
  - [x] [info](https://github.com/indigo-dc/tts_plugin_info)
- [x] checked in compiled ui
- [x] test package building
  - [x] Ubuntu 14.04
  - [x] CentOS 7
- [x] install package and start/stop WaTTS
- [x] test ansible
- [x] set released ansible plugin version
- [x] changelog
- [x] version bump of WaTTS

**Comment by bwegh** [comment]
Direct after release
- [x] set version back to semver after it

**Comment by bwegh** [comment]
list of changes:
https://github.com/indigo-dc/tts/compare/v0.4.1...master

**Comment by bwegh** [comment]
https://github.com/indigo-dc/ansible-role-tts/releases/tag/v1.0.0
